### ISSUE TITLE
Polygon visualisation : don's show arcs if too small

### ISSUE THREAD

**Issue by jan-perl** [ObjectVision/GeoDMS#141] opened 2023-02-09 11:56 UTC
I tried to swtch off arcs in polygon plots. Wiki doesn't tell if this is possible.
I tried:

parameter<int16>  PenWidth      := 0s          , DialogType = "PenWidth";
parameter<meter>  PenWorldWidth := Percentage13K/PenWorldWidth, DialogType = "PenWorldWidth";

What I really would like is a setting in the polygon visualisation: if the PenWorldWidth becomes less than say 1/000 of a pixel, then do not show it. Then, on detailed scales, arcs are shown, and on large scales the arcs do not show instead of the data.

**Comment by jipclaassens** [comment] 2024-02-02 08:39
duplicate of #642

**Closed by jipclaassens** 2024-02-02 08:39 UTC
Labels: enhancement
