### ISSUE TITLE
Unclear error, when creating boolean tif with gdal

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#581] opened 2023-11-10 12:48 UTC
Maybe not allowing writing boolean tif in combination with gdal?

N.B. even with the error, it did create a .tif, with only 0 values...

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e763af7c-f56a-4a30-b25c-ac18cd37568a)

**Comment by eoudejans** [comment] 2023-11-13 08:34
> Maybe not allowing writing boolean tif in combination with gdal?
The [gdal tif driver](https://gdal.org/drivers/raster/gtiff.html#gtiff-geotiff-file-format) only supports: **Byte, UInt16, Int16, UInt32, Int32, Float32, Float64, CInt16, CInt32, CFloat32 and CFloat64**.

> N.B. even with the error, it did create a .tif, with only 0 values...
Likely that on creation the tif driver does not need to know what the pixel value type will be, hence the tif is created but at time of writing an internal geodms check fails.

**Comment by eoudejans** [comment] 2023-11-13 08:39
> Likely that on creation the tif driver does not need to know what the pixel value type will be, hence the tif is created but at time of writing an internal geodms check fails.

Considering my previous comment above, I can confirm that it is indeed that we hard assume that all gdal raster drivers support the set of the gdal tif driver. To be investigated if this is the case. An improvement would be to ask the tif driver itself what data types it supports. This behavior is already implemented for gdal.vect.

**Comment by eoudejans** [comment] 2023-11-13 08:42
In complement to the suggested improvement above, the error message can be made explicit and for instance here changed to something along the lines of:

Gdal GTiff driver does not support value type: Boolean.

**Comment by jipclaassens** [comment] 2023-11-13 11:11
```
attribute<bool> WriteProtoBeschikbaar (AdminDomain) := CalcProtoBeschikbaar, StorageName = "= '%LocalDataProjDir%/VariantData/Beschikbaar/'+Variant_name+'/Zeef/'+name+'/'+Zichtjaar_name+'.tif'", StorageType = "gdalwrite.grid";
```

**Comment by eoudejans** [comment] 2023-11-13 15:25
There was a bug with the value type checking between geodms and gdal raster driver right before creating the dataset; specifically for datatypes with less than 8 bits.

After correcting this issue the error is much more clear:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/f491556d-533d-46a7-a699-81a9afdc65a4)

**Comment by eoudejans** [comment] 2023-11-15 08:14
The error message above should have been provided all along. It was not which was caused by an incorrect translation of GeoDMS values types to GDAL values types, which ended always up as a type that could be exported (for the GTiff driver at least). This is fixed in the latest commit.

All gdal unit tests passed, closing issue as implemented with the improved error checking.

**Closed by eoudejans** 2023-11-15 08:14 UTC
Labels: bug
