### ISSUE TITLE
convert projection works in 8.9.1 but not in 12.2.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#446] opened 2023-08-16 12:47 UTC
conversion from a geometry in EPSG 31300 (belgium) to EPSG 28992 (Netherlands) does work in geodms 8.9.1 but not in 12.2.0.
In 12.2.0 nothing appears in mapview, tableview is empty with only id's.

PD (incl SD) https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon rev10130 (revision numbers matters!)
item: /Vlaanderen/Gemeente_pol/Geometry_rd

8.9.1
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/5dbeae64-30c6-4779-aa04-4bfdfd0da945)
12.2.0
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/5de8bf06-2532-4405-bd93-9207faf6d706)

**Comment by eoudejans** [comment] 2023-08-16 13:15
I hotfixed a very similar issue today. Which followed from the projection check I added monday to determine if the projection given as: provider:code ie. EPGS:4326 is actually a projection and not ie. a datum. Testing as we speak to confirm the issue is resolved or requires more investigation. To be continued..

**Comment by eoudejans** [comment] 2023-08-22 14:39
Issue seems resolved. The tricky part is that the table consists of 300 rows, but some geometries consisted of over 10000+ points, which take some time to convert individually. See:

![coordinate_transform_issue_446](https://github.com/ObjectVision/GeoDMS/assets/96182097/95cf1176-3bbb-491e-9bd1-738ccc12b8f4)

Closing issue as resolved, to be shipped in an upcoming release of GeoDMS.

**Comment by eoudejans** [comment] 2023-08-23 09:26
Reopened issue, performance regression needs further investigation.

**Comment by eoudejans** [comment] 2023-08-23 10:31
From the gdal docs on [OGRCreateCoordinateTransformation](https://gdal.org/api/ogrspatialref.html#_CPPv433OGRCreateCoordinateTransformationPK19OGRSpatialReferencePK19OGRSpatialReferenceRK34OGRCoordinateTransformationOptions), which we use to create the transformation block, it states several available options. 

The OGR_CT_OP_SELECTION appears to be the culprit and default set to PROJ, which means that for every point the best reprojection pipeline is determined, which may involve a Taylor expansion for every area around each point. Changing this option to BEST_ACCURACY makes the code run in a split second again.

**Comment by eoudejans** [comment] 2023-08-23 10:32
Next to the above finding, we also rewritten the coordinate transformation logic to be more clear and efficient, passing in batches of points instead of points separately.

**Comment by eoudejans** [comment] 2023-08-23 11:25
Latest version of GeoDMS will be similar in speed for coordinate transformations compared to version 8.9.1. Furthermore we will add multiple point coordinate transformations to our unit tests to test performance regression in the future.

**Comment by eoudejans** [comment] 2023-08-23 11:47
Make regression test for coordinate transformation of multiple geometries. @mtbeek32

**Comment by mtbeek32** [comment] 2023-08-24 18:18
regression test added to full test.

**Closed by mtbeek32** 2023-08-24 18:18 UTC
Labels: optimization
