### ISSUE TITLE
Fatal OS structured exception in 11.2.0 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#290] opened 2023-06-30 08:21 UTC
ctr+d op
/SourceData/Vastgoed/BAG/PerJaar/Y2012/Panden/Src/status_rel
geeft delphi error en dan fatal exception (Unknown exception code)

Geeft correcte error in 10.0.2

OVSRV6:
C:\ProjDir\Jip\_Github_issues\Datavragen_issueGH290\cfg\main.dms

**Comment by MaartenHilferink** [comment] 2023-07-04 08:09
cannot reproduce (with 11.3.1, release, old-gui):
ctrl+d results in:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0b89a63e-c5eb-4cf4-b49a-a24501531c1b)
and then [Ignore] gives nothing;

**Comment by MaartenHilferink** [comment] 2023-07-04 08:13
with 11.2.0, the issue is reproduced at first try: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/79dd980d-4184-467a-8a32-638c7f5c7050)
so I consider this issue as fixed in 11.3.1

**Closed by MaartenHilferink** 2023-07-04 08:13 UTC
Labels: crash, ovsrv06
