### ISSUE TITLE
activating an item in a template with an unknown unit results in a crash/structured exception

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#606] opened 2023-12-08 14:36 UTC
Steps to reproduce:

geoDMS 14.7.0
prj: MicroTst,

Activate item: template_unknown_unit/T/b in TreeView, application crashes

**Comment by eoudejans** [comment] 2023-12-19 10:46
Crash/structured exception was caused by a nullptr dereference during general detail page retrieval. This is resolved in the latest commit.

At template instantiation the user will be informed that indeed the values unit does not exist, see:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/fbb68227-0782-41bf-abb4-3d3e19509c1f)

**Comment by eoudejans** [comment] 2023-12-19 10:50
Closing issue as resolved.

**Closed by eoudejans** 2023-12-19 10:50 UTC
Labels: crash
