### ISSUE TITLE
Export primary data points: GDAL Error: driver GPKG does not support writing of values type FPoint

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#399] opened 2023-08-03 08:55 UTC
When exporting a point item with export primary data, gpkg I get the error (in event log)
GDAL Error: driver GPKG does not support writing of values type FPoint

PD10044: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon
/RegioIndelingen/centroid_or_mid

same for Ipoint by the way. Polygon items works fine. Something to do with the fact its a point-item?
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/d647b762-67bd-41eb-b7c2-9a4b9ce45d83)

**Comment by eoudejans** [comment] 2023-08-07 18:22
The error in this case should not have occurred, since you are writing only one dataitem to file. The issue is known for domains that contain multiple dataitems that are of type geometry, ie. point, linestring or (multi)polygon. To be further investigated what the cause of this issue is.

**Comment by eoudejans** [comment] 2023-08-07 18:46
Likely related to issue #389.

**Comment by eoudejans** [comment] 2023-08-07 21:21
Likely fixed with fix for issue #389, to be tested/confirmed this now works properly.

**Closed** 2023-08-14 15:06 UTC
Labels: bug
