### ISSUE TITLE
remove carriage return from statistics window

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#493] opened 2023-09-01 08:45 UTC
When copying results from the Statistics window in 13.3.0 I noticed a carriage return is placed between the ID and the Value. Could this be replaced by a tab?

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/6db34acb-181b-42a1-a747-7b653ae9b5f9)

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/b2919aff-24c1-438d-a5e2-59dff58c6353)

**Comment by basvanbemmel** [comment] 2023-09-01 08:48
By the way I also noticed strange behaviour at filling of the values, the first rows are sometimes empty (when direct go to Stats without showing the map)

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/1986f91e-1563-463c-9203-070d18e3920d)

after showing the legend of the map

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/e0bf5112-06dc-4559-b478-6bf73248ffa9)

**Comment by jipclaassens** [comment] 2023-09-01 12:17
Goed punt Bas, linked to #297

**Comment by eoudejans** [comment] 2023-09-06 11:13
Carriage returns are part of how the html is generated. Try for example to copy and paste information from the detail pages and you will notice it also has carriage returns. Carriage return is added when closing a bracket ">", newline is called. We could reconsider this behavior.

**Comment by eoudejans** [comment] 2023-09-06 11:15
> By the way I also noticed strange behaviour at filling of the values, the first rows are sometimes empty (when direct go to Stats without showing the map)
> 
>
> after showing the legend of the map
> 
> 
I can reproduce this behavior, further investigation is needed on why this occurs.

**Comment by basvanbemmel** [comment] 2023-09-06 11:17
I think it has maybe to do if the legend in the map has already been shown or not

**Comment by jipclaassens** [comment] 2023-09-21 07:53
The behaviour of the value count in the statistics is now perfect! It may be intended or unintended. If you want to copy the value counts, you roughly select some and it will select the whole value count table and NOT the sum/mean, etc. Perfect. ctrl+C and ctrl+V in excel gives a perfectly formatted table!

**Comment by basvanbemmel** [comment] 2023-09-27 06:19
Is still an issue in 14.2.0 see screendump. I dont know what Jip checkd but it goes about the value and the count of the statistics window not the part above. I want a tab between the value and the count not an CRLF

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/e52f1606-d2e9-46bc-a7f9-6549876fc5a6)

**Comment by MaartenHilferink** [comment] 2023-09-27 09:12
The DataView contents is rendered-html; we cannot directly change its format without affecting how it is layed-out (as <Table> with <TR>'s and <TD>'s ) and converted to text.

We could add a copy-to-clipboard-as-tab-separated-values button-style link (<A/> ) below the html text with a href that contains an url-encoded instruction to the GeoDms to copy-to-clipboard a tabbed version of the table.

**Comment by basvanbemmel** [comment] 2023-09-27 10:14
I prefer the solution which you propose (we could..... the table). By the way in the old delphi-GUI it worked (tab-delimited)

**Comment by MaartenHilferink** [comment] 2023-09-28 21:35
Implemented:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/24ed2af7-5ead-489c-8315-4d0184e50d1c)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a3bdae31-e8d2-40f0-886a-bfa4f6284a75)

**Closed by MaartenHilferink** 2023-09-28 21:35 UTC
Labels: enhancement

**Comment by MaartenHilferink** [comment] 2023-09-29 11:58
Supplemental click-to-cliboard link for the first table:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/5b6c9820-f295-4d08-8421-e451b74b17cd)
