### ISSUE TITLE
Memory usage info in Statusbar (Committed xxx Max Committed xxx; allocator xxx Highest allocator xxx

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#540] opened 2023-10-13 14:05 UTC
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/14cd7f3b-76d1-4d1d-b896-b2f6ed20c307)

**Comment by MaartenHilferink** [comment] 2023-10-13 14:07
possible format: Committed xxx Max Committed xxx; allocated xxx Highest allocated xxx

**Comment by jipclaassens** [comment] 2023-10-16 08:10
duplicate of #537

**Closed** 2023-10-23 09:05 UTC
Labels: diagnostics, Qt
