### ISSUE TITLE
github wiki contents aren't indexed by search engines.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#192] opened 2023-03-27 14:21 UTC
Affected projects: All that use wiki documentation, especially GeoDMS and GeoDMS_Academy, but also the thematic projects: LandUseModelling and AccessibilityModelling. 

Possible mitigations:
- mirror contents on www.objectvision.nl: 2 downvotes
- move contents back to www.objectvision.nl
- move contents to another content hosting platform
- indicate to github that the currect situation is unacceptable to us
- move to "github pages"

See also: https://github.com/quarkiverse/quarkiverse/issues/93

**Comment by MaartenHilferink** [comment] 2023-03-27 14:21
What are github docs and how do they relate to the .MD format ?

**Comment by jipclaassens** [comment] 2023-10-04 10:01
The readme files in the code are indexed! We should utilise those much more!

**Comment by eoudejans** [comment] 2023-11-13 10:18
Relevant links to convert wiki to gh pages:
https://pages.github.com/

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

**Comment by eoudejans** [comment] 2023-11-13 10:20
Related questions:
- Are github pages findable by ie Google, Yahoo..
- Stategy gh wrt content disclosure in the future?

**Comment by MaartenHilferink** [comment] 2023-11-13 13:11
https://github.com/nelsonjchen/github-wiki-see-rs
https://github-wiki-see.page/

**Comment by MaartenHilferink** [comment] 2023-11-13 14:04
https://chat.openai.com/c/308cf4b9-2759-41ca-a243-740279bbe1a7

**Comment by MaartenHilferink** [comment] 2023-11-13 14:14
github-wiki-see.page does partly resolve this issue, see for example the 3rd entry when google searching for:
`github geodms impedance matrix`
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/205a79de-0668-4d40-905b-967277d8031a)

Note that the 4th entry is a github readme.MD

**Comment by eoudejans** [comment] 2023-11-30 22:04
Conversion from GeoDMS Github wiki to static html is now available in [https://github.com/ObjectVision/GeoDmsWikiToStaticHtml](https://github.com/ObjectVision/GeoDmsWikiToStaticHtml)

Our Github wiki remains the main source for our documentation but allows for porting the content to another host, which enables indexing.

Some screenshots:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/9c81b029-40ec-4ff7-9fef-7c1398bea9df)

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/cc3d8b73-66bd-4163-aac5-6e856747c0ed)

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/42678630-309c-4dec-984f-f235509013ae)

To be further experimented how to properly host the static html content.

**Comment by eoudejans** [comment] 2024-01-09 10:21
Finalized port of GeoDms wiki on Github. Result is live and can be found at: https://geodms.nl/

**Comment by eoudejans** [comment] 2024-01-11 11:14
@mtbeek32 final step is request reindexing from Google: https://support.google.com/webmasters/answer/9012289#request_indexing

Already the first link in my search for geodms resulted in a working link:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6b9b81b8-dcf2-48fe-8096-ed0590ed9201)

**Comment by eoudejans** [comment] 2024-01-29 13:09
Duplicate of issue #625

**Closed** 2024-03-15 09:55 UTC
Labels: documentation
