### ISSUE TITLE
When clicking on colour in palette of pointset in mapview, value info emerges instead of edit colour

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#376] opened 2023-07-28 08:13 UTC
When clicking on colour in palette of pointset in mapview, value info emerges instead of edit colour

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/6a00dece-9fde-414d-a8d7-d5471137d904)

**Comment by jipclaassens** [comment] 2023-07-28 12:00
maybe in the same fix, look at #116

**Comment by MaartenHilferink** [comment] 2023-08-22 08:49
Unable to reproduce:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/6123232b-e10d-4797-96af-60c20184f850)

**Comment by jipclaassens** [comment] 2023-08-22 09:15
Deze werkt wel, want is grid:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/6aa1785d-bb72-4f0d-91d6-6f91bca210e2)

Maar, deze als resultaat van een select_with_attr niet:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/889df74e-0c05-458f-91a4-22617b554cd1)

**Comment by jipclaassens** [comment] 2023-08-22 09:44
cfg: AccessibilityModelling
pad: /SourceData/Locaties/Huisartsenposten/HeeftHuisartsenposten/Count_per_domain

**Comment by MaartenHilferink** [comment] 2023-08-22 10:14
Fixed in 13.0.0
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3b87976f-50fc-4468-9807-947b1afb4a35)

**Closed by MaartenHilferink** 2023-08-22 10:14 UTC
Labels: bug, Qt
