### ISSUE TITLE
Script Editor, parameters from separate control

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#433] opened 2023-08-14 11:36 UTC
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/eb2255fc-2706-4664-bd6d-dad2c9d2d6de)

- Parameters should be moved from Application to Parameters control. 
- Button Set default parameters for application should set default parameters for Notepad/Crimson Editor, see:  https://github.com/ObjectVision/GeoDMS/wiki/Configuration-File-Editor

**Comment by jipclaassens** [comment] 2023-08-14 15:31
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e3797821-bee4-42ba-a18e-24bdb1d1e4a9)

**Comment by eoudejans** [comment] 2023-08-15 10:59
Editor program path is now separated from editor command line arguments.
![editor_path_split](https://github.com/ObjectVision/GeoDMS/assets/96182097/5b85c7bd-926c-42dc-8295-723833ed568e)

**Comment by eoudejans** [comment] 2023-08-15 11:12
If Qt is unable to start the editor command detached, it will now result in a warning, for instance the following warning caused by a non-quoted editor exe file:
![editor_invalid_start_warning](https://github.com/ObjectVision/GeoDMS/assets/96182097/18b293ad-9a64-4453-9b6d-ba4693e1e26f)

**Comment by eoudejans** [comment] 2023-08-15 11:24
Also implemented default parameters for notepad++ and crimson editors. Closing issue as implemented.

**Closed by eoudejans** 2023-08-15 11:24 UTC
Labels: Qt
