### ISSUE TITLE
View menu crashes

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#450] opened 2023-08-18 07:41 UTC
Opening the View menu in 12.4.0 results in a crash

**Comment by eoudejans** [comment] 2023-08-21 10:42
View menu crash caused by added logic to check if item was in template. However, on startup the current item is nullptr which caused dereferencing of nullptr and hence the crash.

Closing issue as fixed.

**Closed by eoudejans** 2023-08-21 10:42 UTC
Labels: crash
