### ISSUE TITLE
WMTS request fails with asio error when there is no internet connection

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#135] opened 2023-02-08 10:08 UTC
When mapview with WMTS background layer is viewed, and the user has no internet connection, an error is thrown.
This should be changed to a warning, as GeoDMS is able to continue work without a WMTS background layer.

Possible solution: as long the user views a mapview with WMTS background layer and has no internet check every ~10 seconds if internet connection has been reestablished, if not, continue.

**Comment by MaartenHilferink** [comment] 2023-04-17 13:04
Possible solution seems too complicated. User can easily trigger a redraw when an Internet connection has been restored and for error reporting, this is a duplicate of #208.

**Closed by MaartenHilferink** 2023-04-17 13:04 UTC
Labels: bug
