### ISSUE TITLE
Apply new naming standard to family of geometric functions

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#185] opened 2023-03-23 10:22 UTC
For example: the split_partitioned_union_polygon operator generates a nr_OrgEntity

**Comment by MaartenHilferink** [comment] 2023-03-23 11:51
@jipclaassens Can you elaborate and propose new names ? In casu, for example, 'partition_rel', but for split_polygon: 'polygon_rel', etc.

**Comment by MaartenHilferink** [comment] 2023-03-27 13:47
Duplicate of #165

**Closed by MaartenHilferink** 2023-03-27 13:47 UTC
Labels: enhancement
